languageCode = "en-us"
baseurl = "https://snlab-freedom.github.io/"
title = "SNLab Freedom Zone"
theme = "hugo-theme-cooler"
disqusShortname = ""
googleAnalytics = ""
paginate = 10

# Single post link format
[permalinks]
    post = "/:year/:month/:day/:slug"

# Footer content
[params]
    # Tell me who you're
    location = ""
    site_description = ""
    organization = "SNLab.Freedom"
    organization_url = "https://github.com/snlab_freedom"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [cooler](https://gitlab.com/snlab-freedom/hugo-theme-cooler)."

    # Format dates with Go's time formating
    date_format = "2006-01-02"

    # Meta data for your website
    title = "SNLab"
    subtitle = "Freedom"

# Main.Menus
[[menu.main]]
    name  = "Home"
    identifier = "home"
    url = "/"
    weight = 0

[[menu.main]]
    name  = "Projects"
    identifier = "projects"
    weight = 100

[[menu.main]]
    name  = "Paper Study"
    identifier = "paper-study"
    url = "/paper-study"
    weight = 110

[[menu.main]]
    name   = "Posts"
    url    = "/posts"
    identifier = "posts"
    weight = 200

[[menu.main]]
    name = "Members"
    identifier = "members"
    url = "/members"
    weight = 300

[[menu.main]]
    name  = "Publications"
    url   = "/publications"
    identifier = "publications"
    weight = 400

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 500

# Sidebar Documentation content
[[params.widget.documentation]]
    name = "Demos"
    url = "/demos"
[[params.widget.documentation]]
    name = "Tutorials"
    url = "/tutorials"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = ""

# Article First Content
[params.article_first]
    title = "Welcome to SNLab Freedom Zone!"
    body = [
    "You've reached the website for Freedom Zone of Systems Networking Lab (SNLab.Freedom).",
    "Founded by Professor Y. Richard Yang <http://www.cs.yale.edu/homes/yry/> in the summer of 2014, and hosted in the Institute of Advanced Studies at Tongji University, the Systems Networking Lab (SNLab) will provide astimulating, world-class environment for the advancement of both theory and systems of networks and networked systems."
    ]
    rss_show = true

# Members
[[params.members]]
    position = "Directors"
[[params.members]]
    position = "Faculty"
[[params.members]]
    position = "Postdocs"
[[params.members]]
    position = "Graduate Students"
[[params.members]]
    position = "Undergraduates"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "snlab-freedom"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = "UCgUGS8ggkCKmyppiFqEtidA"
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = "117843142371942012323"
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""
# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
    download = false
    documentation = true
